/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const $apiPath: typeof import('~/context').$apiPath
  const $cspNonce: typeof import('~/context').$cspNonce
  const $fetch: typeof import('~/context').$fetch
  const $sitePath: typeof import('~/context').$sitePath
  const $uiConfig: typeof import('~/context').$uiConfig
  const AUTONOMOUS_AGENT_WRITABLE_KEYS: typeof import('../src/utils/autonomous-agent-draft').AUTONOMOUS_AGENT_WRITABLE_KEYS
  const CHARS_PER_TOKEN: typeof import('../src/utils/compaction-policy').CHARS_PER_TOKEN
  const DEFAULT_FLAGS: typeof import('../src/utils/agent-flags').DEFAULT_FLAGS
  const DEFAULT_REFUSAL: typeof import('../src/composables/moderation')['DEFAULT_REFUSAL']
  const EXPLORE_TOOL_NAME: typeof import('../src/utils/tool-exploration').EXPLORE_TOOL_NAME
  const EffectScope: typeof import('vue').EffectScope
  const FLAGS_COOKIE: typeof import('../src/utils/agent-flags').FLAGS_COOKIE
  const FLOOR_SHARE: typeof import('../src/utils/compaction-policy').FLOOR_SHARE
  const HOST_EVENTS_CLOSE: typeof import('../src/composables/host-events').HOST_EVENTS_CLOSE
  const HOST_EVENTS_OPEN: typeof import('../src/composables/host-events').HOST_EVENTS_OPEN
  const HOST_STATE_CLOSE: typeof import('../src/composables/host-events').HOST_STATE_CLOSE
  const HOST_STATE_OPEN: typeof import('../src/composables/host-events').HOST_STATE_OPEN
  const HostEventStore: typeof import('../src/composables/host-events').HostEventStore
  const LOCATION_KEY: typeof import('../src/composables/host-events').LOCATION_KEY
  const MERMAID_AUTO_FIX_BUDGET: typeof import('../src/utils/mermaid-fix').MERMAID_AUTO_FIX_BUDGET
  const MODERATION_TASK_MARKER: typeof import('../src/composables/moderation')['MODERATION_TASK_MARKER']
  const PENDING_MAX: typeof import('../src/composables/host-events').PENDING_MAX
  const RECENT_MAX: typeof import('../src/composables/host-events').RECENT_MAX
  const REPEATED_CALL_LIMIT: typeof import('../src/composables/agent-loop-guards').REPEATED_CALL_LIMIT
  const REPEATED_CALL_NUDGE_AT: typeof import('../src/composables/agent-loop-guards').REPEATED_CALL_NUDGE_AT
  const RETENTION_SHARE: typeof import('../src/utils/compaction-policy').RETENTION_SHARE
  const SELECT_TOOL_NAME: typeof import('../src/utils/tool-exploration').SELECT_TOOL_NAME
  const STATE_MAX_KEYS: typeof import('../src/composables/host-events').STATE_MAX_KEYS
  const STEP_LIMIT: typeof import('../src/composables/agent-loop-guards').STEP_LIMIT
  const SUBAGENT_DONE_FALLBACK: typeof import('../src/utils/agent-subagent-output').SUBAGENT_DONE_FALLBACK
  const SUBAGENT_MODERATION_NOTICE: typeof import('../src/utils/agent-subagent-output').SUBAGENT_MODERATION_NOTICE
  const SUBAGENT_PARTIAL_PREFIX: typeof import('../src/utils/agent-subagent-output').SUBAGENT_PARTIAL_PREFIX
  const SUBAGENT_STEP_LIMIT_NOTICE: typeof import('../src/utils/agent-subagent-output').SUBAGENT_STEP_LIMIT_NOTICE
  const TOOL_ARGUMENTS_LIMIT: typeof import('../src/utils/tool-arguments').TOOL_ARGUMENTS_LIMIT
  const WAIT_DEFAULT_SECONDS: typeof import('../src/composables/host-events').WAIT_DEFAULT_SECONDS
  const WAIT_MAX_SECONDS: typeof import('../src/composables/host-events').WAIT_MAX_SECONDS
  const WAIT_TOOL_NAME: typeof import('../src/composables/host-events').WAIT_TOOL_NAME
  const activityLabelKey: typeof import('../src/composables/agent-activity').activityLabelKey
  const appendHostEvents: typeof import('../src/composables/host-events').appendHostEvents
  const appendStreamingCaret: typeof import('../src/utils/markdown').appendStreamingCaret
  const applyStreamPart: typeof import('../src/utils/agent-stream-parts').applyStreamPart
  const autonomousAgentEditDraft: typeof import('../src/utils/autonomous-agent-draft').autonomousAgentEditDraft
  const autonomousAgentMessageToChat: typeof import('../src/utils/autonomous-agent-chat-message').autonomousAgentMessageToChat
  const breadcrumbs: typeof import('../src/utils/breadcrumbs').default
  const breakdownDatasets: typeof import('../src/utils/usage-breakdown').breakdownDatasets
  const buildMermaidThemeVariables: typeof import('../src/utils/mermaid').buildMermaidThemeVariables
  const buildModerationSystemPrompt: typeof import('../src/composables/moderation')['buildModerationSystemPrompt']
  const canSendNow: typeof import('../src/composables/chat-send').canSendNow
  const computed: typeof import('vue').computed
  const computedDeepDiff: typeof import('@data-fair/lib-vue/deep-diff.js').computedDeepDiff
  const createApp: typeof import('vue').createApp
  const createExploreTool: typeof import('../src/utils/tool-exploration').createExploreTool
  const createReactiveSearchParams: typeof import('../src/composables/use-webmcp')['createReactiveSearchParams']
  const createRouter: typeof import('vue-router').createRouter
  const createToolTitleMemo: typeof import('../src/composables/tool-titles').createToolTitleMemo
  const createWaitTool: typeof import('../src/composables/host-events').createWaitTool
  const createWebHistory: typeof import('vue-router').createWebHistory
  const customRef: typeof import('vue').customRef
  const decideCompaction: typeof import('../src/utils/compaction-policy').decideCompaction
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const dfDateMatchFilter: typeof import('@data-fair/lib-vuetify/date-match-filter.vue')['default']
  const dfDateRangePicker: typeof import('@data-fair/lib-vuetify/date-range-picker.vue')['default']
  const dfLangSwitcher: typeof import('@data-fair/lib-vuetify/lang-switcher.vue')['default']
  const dfNavigationRight: typeof import('@data-fair/lib-vuetify/navigation-right.vue')['default']
  const dfOwnerAvatar: typeof import('@data-fair/lib-vuetify/owner-avatar.vue')['default']
  const dfOwnerPick: typeof import('@data-fair/lib-vuetify/owner-pick.vue')['default']
  const dfPersonalMenu: typeof import('@data-fair/lib-vuetify/personal-menu.vue')['default']
  const dfThemeSwitcher: typeof import('@data-fair/lib-vuetify/theme-switcher.vue')['default']
  const dfTutorialAlert: typeof import('@data-fair/lib-vuetify/tutorial-alert.vue')['default']
  const dfUiNotif: typeof import('@data-fair/lib-vuetify/ui-notif.vue')['default']
  const dfUiNotifAlert: typeof import('@data-fair/lib-vuetify/ui-notif-alert.vue')['default']
  const dfUserAvatar: typeof import('@data-fair/lib-vuetify/ui-user-avatar.vue')['default']
  const effectScope: typeof import('vue').effectScope
  const enrolmentErrorMessage: typeof import('../src/utils/autonomous-agent-enrolment-error').enrolmentErrorMessage
  const estimateMessageTokens: typeof import('../src/utils/compaction-policy').estimateMessageTokens
  const estimateTokens: typeof import('../src/utils/compaction-policy').estimateTokens
  const extractErrorMessage: typeof import('../src/utils/error').extractErrorMessage
  const formatBreakdownValue: typeof import('../src/utils/usage-breakdown').formatBreakdownValue
  const formatBytes: typeof import('@data-fair/lib-vue/format/bytes.js').formatBytes
  const formatCredits: typeof import('../src/utils/credits').formatCredits
  const formatHostEvents: typeof import('../src/composables/host-events').formatHostEvents
  const formatHostState: typeof import('../src/composables/host-events').formatHostState
  const formatMcpToolResult: typeof import('../src/utils/tool-result').formatMcpToolResult
  const formatMermaidFix: typeof import('../src/utils/mermaid-fix').formatMermaidFix
  const formatToolsAvailableMessage: typeof import('../src/utils/tool-exploration').formatToolsAvailableMessage
  const getAnonymousToken: typeof import('../src/composables/use-anonymous-token').getAnonymousToken
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const h: typeof import('vue').h
  const hasHostState: typeof import('../src/composables/host-events').hasHostState
  const inject: typeof import('vue').inject
  const injectHead: typeof import('@unhead/vue').injectHead
  const isEmptyTurn: typeof import('../src/composables/empty-turn').isEmptyTurn
  const isMediaToolResult: typeof import('../src/utils/tool-result').isMediaToolResult
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isRepeatingCalls: typeof import('../src/composables/agent-loop-guards').isRepeatingCalls
  const isShallow: typeof import('vue').isShallow
  const isTurnBoundary: typeof import('../src/utils/compaction-policy').isTurnBoundary
  const looksLikeIncompleteTable: typeof import('../src/utils/markdown').looksLikeIncompleteTable
  const loopGuardPrepareStep: typeof import('../src/composables/agent-loop-guards').loopGuardPrepareStep
  const markRaw: typeof import('vue').markRaw
  const mergeBySeq: typeof import('../src/utils/autonomous-agent-chat-message').mergeBySeq
  const messagesToChat: typeof import('../src/utils/autonomous-agent-chat-message').messagesToChat
  const newlyAvailableTools: typeof import('../src/utils/tool-exploration').newlyAvailableTools
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const parseModerationVerdict: typeof import('../src/composables/moderation')['parseModerationVerdict']
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const reactiveSearchParamsKey: typeof import('../src/composables/use-webmcp')['reactiveSearchParamsKey']
  const readFlags: typeof import('../src/utils/agent-flags')['readFlags']
  const readonly: typeof import('vue').readonly
  const reconcileTools: typeof import('../src/composables/live-tools').reconcileTools
  const redactHistoryMediaToolResults: typeof import('../src/utils/tool-result').redactHistoryMediaToolResults
  const redactMediaToolResult: typeof import('../src/utils/tool-result').redactMediaToolResult
  const ref: typeof import('vue').ref
  const renderMarkdown: typeof import('../src/utils/markdown').renderMarkdown
  const renderMermaidIn: typeof import('../src/utils/mermaid').renderMermaidIn
  const renderStreamingMarkdown: typeof import('../src/utils/markdown').renderStreamingMarkdown
  const repairInline: typeof import('../src/utils/markdown').repairInline
  const repeatedCallGuard: typeof import('../src/composables/agent-loop-guards').repeatedCallGuard
  const repeatedCallNudge: typeof import('../src/composables/agent-loop-guards').repeatedCallNudge
  const resetAnonymousToken: typeof import('../src/composables/use-anonymous-token').resetAnonymousToken
  const resolveComponent: typeof import('vue').resolveComponent
  const resolveToolsPartition: typeof import('../src/utils/tools-partition').resolveToolsPartition
  const resolvesWait: typeof import('../src/composables/host-events').resolvesWait
  const retainedToolNames: typeof import('../src/utils/compaction-policy').retainedToolNames
  const selectPromotions: typeof import('../src/utils/tool-exploration').selectPromotions
  const serializeFlagsCookie: typeof import('../src/utils/agent-flags').serializeFlagsCookie
  const setBreadcrumbs: typeof import('../src/utils/breadcrumbs').setBreadcrumbs
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const shouldAutoFixMermaid: typeof import('../src/utils/mermaid-fix').shouldAutoFixMermaid
  const shouldFlattenSubAgent: typeof import('../src/composables/sub-agent-flatten').shouldFlattenSubAgent
  const streamingSafeBuffer: typeof import('../src/utils/markdown').streamingSafeBuffer
  const subAgentModelOutput: typeof import('../src/utils/agent-subagent-output').subAgentModelOutput
  const subscribeHostEvents: typeof import('../src/composables/use-host-events').subscribeHostEvents
  const summarizeToolArguments: typeof import('../src/utils/tool-arguments').summarizeToolArguments
  const toDescriptors: typeof import('../src/composables/use-agent-session').toDescriptors
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const trailingRepeatCount: typeof import('../src/composables/agent-loop-guards').trailingRepeatCount
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAgentChat: typeof import('../src/composables/use-agent-chat').useAgentChat
  const useAgentEvaluator: typeof import('../src/composables/use-agent-evaluator')['default']
  const useAgentSession: typeof import('../src/composables/use-agent-session').useAgentSession
  const useAsyncAction: typeof import('@data-fair/lib-vue/async-action.js').useAsyncAction
  const useAttrs: typeof import('vue').useAttrs
  const useAutonomousAgentEnrolment: typeof import('../src/composables/use-autonomous-agent-enrolment').useAutonomousAgentEnrolment
  const useBooleanSearchParam: typeof import('@data-fair/lib-vue/reactive-search-params.js').useBooleanSearchParam
  const useConceptFilters: typeof import('@data-fair/lib-vue/concept-filters.js').useConceptFilters
  const useConversation: typeof import('../src/composables/use-autonomous-agent-conversation').useConversation
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useEditFetch: typeof import('@data-fair/lib-vue/edit-fetch.js').useEditFetch
  const useFetch: typeof import('@data-fair/lib-vue/fetch.js').useFetch
  const useFrameServer: typeof import('../src/composables/use-frame-server')['useFrameServer']
  const useFrameTools: typeof import('../src/composables/use-frame-tools').useFrameTools
  const useHead: typeof import('@unhead/vue').useHead
  const useHeadSafe: typeof import('@unhead/vue').useHeadSafe
  const useHostEvents: typeof import('../src/composables/use-host-events').useHostEvents
  const useI18n: typeof import('vue-i18n').useI18n
  const useId: typeof import('vue').useId
  const useLeaveGuard: typeof import('@data-fair/lib-vue/leave-guard.js').useLeaveGuard
  const useLink: typeof import('vue-router').useLink
  const useLocaleDayjs: typeof import('@data-fair/lib-vue/locale-dayjs.js').useLocaleDayjs
  const useModel: typeof import('vue').useModel
  const useNumberSearchParam: typeof import('@data-fair/lib-vue/reactive-search-params.js').useNumberSearchParam
  const useReactiveSearchParams: typeof import('@data-fair/lib-vue/reactive-search-params.js').useReactiveSearchParams
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSeoMeta: typeof import('@unhead/vue').useSeoMeta
  const useServerHead: typeof import('@unhead/vue')['useServerHead']
  const useServerHeadSafe: typeof import('@unhead/vue')['useServerHeadSafe']
  const useServerSeoMeta: typeof import('@unhead/vue')['useServerSeoMeta']
  const useSession: typeof import('@data-fair/lib-vue/session.js').useSession
  const useSessionAuthenticated: typeof import('@data-fair/lib-vue/session.js').useSessionAuthenticated
  const useSessionChat: typeof import('../src/composables/use-session-chat').useSessionChat
  const useSettingsForm: typeof import('../src/composables/use-settings-form').useSettingsForm
  const useSlots: typeof import('vue').useSlots
  const useStringSearchParam: typeof import('@data-fair/lib-vue/reactive-search-params.js').useStringSearchParam
  const useStringsArraySearchParam: typeof import('@data-fair/lib-vue/reactive-search-params.js').useStringsArraySearchParam
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useUiNotif: typeof import('@data-fair/lib-vue/ui-notif.js').useUiNotif
  const useWS: typeof import('@data-fair/lib-vue/ws.js').useWS
  const watch: typeof import('vue').watch
  const watchDeepDiff: typeof import('@data-fair/lib-vue/deep-diff.js').watchDeepDiff
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
  const withUiNotif: typeof import('@data-fair/lib-vue/ui-notif.js').withUiNotif
  const writeFlags: typeof import('../src/utils/agent-flags').writeFlags
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { AgentFlags } from '../src/utils/agent-flags'
  import('../src/utils/agent-flags')
  // @ts-ignore
  export type { StoredConversationMessage, AutonomousAgentPart } from '../src/utils/autonomous-agent-chat-message'
  import('../src/utils/autonomous-agent-chat-message')
  // @ts-ignore
  export type { ChatMessage } from '../src/utils/chat-message'
  import('../src/utils/chat-message')
  // @ts-ignore
  export type { MermaidAutoFixState } from '../src/utils/mermaid-fix'
  import('../src/utils/mermaid-fix')
  // @ts-ignore
  export type { MermaidFailure } from '../src/utils/mermaid'
  import('../src/utils/mermaid')
  // @ts-ignore
  export type { ToolInfo, SubAgentInfo, DebugToolsPartition } from '../src/utils/tools-partition'
  import('../src/utils/tools-partition')
  // @ts-ignore
  export type { UsageDimension, UsageEntry } from '../src/utils/usage-breakdown'
  import('../src/utils/usage-breakdown')
  // @ts-ignore
  export type { TurnTextState } from '../src/composables/empty-turn'
  import('../src/composables/empty-turn')
  // @ts-ignore
  export type { ToolsDelta } from '../src/composables/live-tools'
  import('../src/composables/live-tools')
  // @ts-ignore
  export type { AgentSessionClientOptions } from '../src/composables/use-agent-session'
  import('../src/composables/use-agent-session')
  // @ts-ignore
  export type { ConversationOptions } from '../src/composables/use-autonomous-agent-conversation'
  import('../src/composables/use-autonomous-agent-conversation')
  // @ts-ignore
  export type { OrgNhi } from '../src/composables/use-autonomous-agent-enrolment'
  import('../src/composables/use-autonomous-agent-enrolment')
  // @ts-ignore
  export type { UseSessionChatOptions } from '../src/composables/use-session-chat'
  import('../src/composables/use-session-chat')
  // @ts-ignore
  export type { SettingsFormParams } from '../src/composables/use-settings-form'
  import('../src/composables/use-settings-form')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly $apiPath: UnwrapRef<typeof import('~/context')['$apiPath']>
    readonly $cspNonce: UnwrapRef<typeof import('~/context')['$cspNonce']>
    readonly $fetch: UnwrapRef<typeof import('~/context')['$fetch']>
    readonly $sitePath: UnwrapRef<typeof import('~/context')['$sitePath']>
    readonly $uiConfig: UnwrapRef<typeof import('~/context')['$uiConfig']>
    readonly AUTONOMOUS_AGENT_WRITABLE_KEYS: UnwrapRef<typeof import('../src/utils/autonomous-agent-draft')['AUTONOMOUS_AGENT_WRITABLE_KEYS']>
    readonly DEFAULT_FLAGS: UnwrapRef<typeof import('../src/utils/agent-flags')['DEFAULT_FLAGS']>
    readonly EXPLORE_TOOL_NAME: UnwrapRef<typeof import('../src/utils/tool-exploration')['EXPLORE_TOOL_NAME']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly FLAGS_COOKIE: UnwrapRef<typeof import('../src/utils/agent-flags')['FLAGS_COOKIE']>
    readonly MERMAID_AUTO_FIX_BUDGET: UnwrapRef<typeof import('../src/utils/mermaid-fix')['MERMAID_AUTO_FIX_BUDGET']>
    readonly SELECT_TOOL_NAME: UnwrapRef<typeof import('../src/utils/tool-exploration')['SELECT_TOOL_NAME']>
    readonly TOOL_ARGUMENTS_LIMIT: UnwrapRef<typeof import('../src/utils/tool-arguments')['TOOL_ARGUMENTS_LIMIT']>
    readonly appendStreamingCaret: UnwrapRef<typeof import('../src/utils/markdown')['appendStreamingCaret']>
    readonly autonomousAgentEditDraft: UnwrapRef<typeof import('../src/utils/autonomous-agent-draft')['autonomousAgentEditDraft']>
    readonly autonomousAgentMessageToChat: UnwrapRef<typeof import('../src/utils/autonomous-agent-chat-message')['autonomousAgentMessageToChat']>
    readonly breadcrumbs: UnwrapRef<typeof import('../src/utils/breadcrumbs')['default']>
    readonly breakdownDatasets: UnwrapRef<typeof import('../src/utils/usage-breakdown')['breakdownDatasets']>
    readonly buildMermaidThemeVariables: UnwrapRef<typeof import('../src/utils/mermaid')['buildMermaidThemeVariables']>
    readonly canSendNow: UnwrapRef<typeof import('../src/composables/chat-send')['canSendNow']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly computedDeepDiff: UnwrapRef<typeof import('@data-fair/lib-vue/deep-diff.js')['computedDeepDiff']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createExploreTool: UnwrapRef<typeof import('../src/utils/tool-exploration')['createExploreTool']>
    readonly createToolTitleMemo: UnwrapRef<typeof import('../src/composables/tool-titles')['createToolTitleMemo']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly enrolmentErrorMessage: UnwrapRef<typeof import('../src/utils/autonomous-agent-enrolment-error')['enrolmentErrorMessage']>
    readonly extractErrorMessage: UnwrapRef<typeof import('../src/utils/error')['extractErrorMessage']>
    readonly formatBreakdownValue: UnwrapRef<typeof import('../src/utils/usage-breakdown')['formatBreakdownValue']>
    readonly formatBytes: UnwrapRef<typeof import('@data-fair/lib-vue/format/bytes.js')['formatBytes']>
    readonly formatCredits: UnwrapRef<typeof import('../src/utils/credits')['formatCredits']>
    readonly formatMermaidFix: UnwrapRef<typeof import('../src/utils/mermaid-fix')['formatMermaidFix']>
    readonly formatToolsAvailableMessage: UnwrapRef<typeof import('../src/utils/tool-exploration')['formatToolsAvailableMessage']>
    readonly getAnonymousToken: UnwrapRef<typeof import('../src/composables/use-anonymous-token')['getAnonymousToken']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly injectHead: UnwrapRef<typeof import('@unhead/vue')['injectHead']>
    readonly isEmptyTurn: UnwrapRef<typeof import('../src/composables/empty-turn')['isEmptyTurn']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly looksLikeIncompleteTable: UnwrapRef<typeof import('../src/utils/markdown')['looksLikeIncompleteTable']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly mergeBySeq: UnwrapRef<typeof import('../src/utils/autonomous-agent-chat-message')['mergeBySeq']>
    readonly messagesToChat: UnwrapRef<typeof import('../src/utils/autonomous-agent-chat-message')['messagesToChat']>
    readonly newlyAvailableTools: UnwrapRef<typeof import('../src/utils/tool-exploration')['newlyAvailableTools']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly reconcileTools: UnwrapRef<typeof import('../src/composables/live-tools')['reconcileTools']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly renderMarkdown: UnwrapRef<typeof import('../src/utils/markdown')['renderMarkdown']>
    readonly renderMermaidIn: UnwrapRef<typeof import('../src/utils/mermaid')['renderMermaidIn']>
    readonly renderStreamingMarkdown: UnwrapRef<typeof import('../src/utils/markdown')['renderStreamingMarkdown']>
    readonly repairInline: UnwrapRef<typeof import('../src/utils/markdown')['repairInline']>
    readonly resetAnonymousToken: UnwrapRef<typeof import('../src/composables/use-anonymous-token')['resetAnonymousToken']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly resolveToolsPartition: UnwrapRef<typeof import('../src/utils/tools-partition')['resolveToolsPartition']>
    readonly selectPromotions: UnwrapRef<typeof import('../src/utils/tool-exploration')['selectPromotions']>
    readonly serializeFlagsCookie: UnwrapRef<typeof import('../src/utils/agent-flags')['serializeFlagsCookie']>
    readonly setBreadcrumbs: UnwrapRef<typeof import('../src/utils/breadcrumbs')['setBreadcrumbs']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly shouldAutoFixMermaid: UnwrapRef<typeof import('../src/utils/mermaid-fix')['shouldAutoFixMermaid']>
    readonly streamingSafeBuffer: UnwrapRef<typeof import('../src/utils/markdown')['streamingSafeBuffer']>
    readonly subscribeHostEvents: UnwrapRef<typeof import('../src/composables/use-host-events')['subscribeHostEvents']>
    readonly summarizeToolArguments: UnwrapRef<typeof import('../src/utils/tool-arguments')['summarizeToolArguments']>
    readonly toDescriptors: UnwrapRef<typeof import('../src/composables/use-agent-session')['toDescriptors']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly useAgentSession: UnwrapRef<typeof import('../src/composables/use-agent-session')['useAgentSession']>
    readonly useAsyncAction: UnwrapRef<typeof import('@data-fair/lib-vue/async-action.js')['useAsyncAction']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useAutonomousAgentEnrolment: UnwrapRef<typeof import('../src/composables/use-autonomous-agent-enrolment')['useAutonomousAgentEnrolment']>
    readonly useBooleanSearchParam: UnwrapRef<typeof import('@data-fair/lib-vue/reactive-search-params.js')['useBooleanSearchParam']>
    readonly useConceptFilters: UnwrapRef<typeof import('@data-fair/lib-vue/concept-filters.js')['useConceptFilters']>
    readonly useConversation: UnwrapRef<typeof import('../src/composables/use-autonomous-agent-conversation')['useConversation']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useEditFetch: UnwrapRef<typeof import('@data-fair/lib-vue/edit-fetch.js')['useEditFetch']>
    readonly useFetch: UnwrapRef<typeof import('@data-fair/lib-vue/fetch.js')['useFetch']>
    readonly useFrameTools: UnwrapRef<typeof import('../src/composables/use-frame-tools')['useFrameTools']>
    readonly useHead: UnwrapRef<typeof import('@unhead/vue')['useHead']>
    readonly useHeadSafe: UnwrapRef<typeof import('@unhead/vue')['useHeadSafe']>
    readonly useI18n: UnwrapRef<typeof import('vue-i18n')['useI18n']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useLeaveGuard: UnwrapRef<typeof import('@data-fair/lib-vue/leave-guard.js')['useLeaveGuard']>
    readonly useLink: UnwrapRef<typeof import('vue-router')['useLink']>
    readonly useLocaleDayjs: UnwrapRef<typeof import('@data-fair/lib-vue/locale-dayjs.js')['useLocaleDayjs']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useNumberSearchParam: UnwrapRef<typeof import('@data-fair/lib-vue/reactive-search-params.js')['useNumberSearchParam']>
    readonly useReactiveSearchParams: UnwrapRef<typeof import('@data-fair/lib-vue/reactive-search-params.js')['useReactiveSearchParams']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useSeoMeta: UnwrapRef<typeof import('@unhead/vue')['useSeoMeta']>
    readonly useSession: UnwrapRef<typeof import('@data-fair/lib-vue/session.js')['useSession']>
    readonly useSessionAuthenticated: UnwrapRef<typeof import('@data-fair/lib-vue/session.js')['useSessionAuthenticated']>
    readonly useSessionChat: UnwrapRef<typeof import('../src/composables/use-session-chat')['useSessionChat']>
    readonly useSettingsForm: UnwrapRef<typeof import('../src/composables/use-settings-form')['useSettingsForm']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useStringSearchParam: UnwrapRef<typeof import('@data-fair/lib-vue/reactive-search-params.js')['useStringSearchParam']>
    readonly useStringsArraySearchParam: UnwrapRef<typeof import('@data-fair/lib-vue/reactive-search-params.js')['useStringsArraySearchParam']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useUiNotif: UnwrapRef<typeof import('@data-fair/lib-vue/ui-notif.js')['useUiNotif']>
    readonly useWS: UnwrapRef<typeof import('@data-fair/lib-vue/ws.js')['useWS']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchDeepDiff: UnwrapRef<typeof import('@data-fair/lib-vue/deep-diff.js')['watchDeepDiff']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
    readonly withUiNotif: UnwrapRef<typeof import('@data-fair/lib-vue/ui-notif.js')['withUiNotif']>
    readonly writeFlags: UnwrapRef<typeof import('../src/utils/agent-flags')['writeFlags']>
  }
}