/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/_dev/chat': RouteRecordInfo<'/_dev/chat', '/_dev/chat', Record<never, never>, Record<never, never>>,
    '/_dev/chat-drawer': RouteRecordInfo<'/_dev/chat-drawer', '/_dev/chat-drawer', Record<never, never>, Record<never, never>>,
    '/_dev/chat-iframe': RouteRecordInfo<'/_dev/chat-iframe', '/_dev/chat-iframe', Record<never, never>, Record<never, never>>,
    '/_dev/chat-iframe-2': RouteRecordInfo<'/_dev/chat-iframe-2', '/_dev/chat-iframe-2', Record<never, never>, Record<never, never>>,
    '/_dev/chat-iframe-child': RouteRecordInfo<'/_dev/chat-iframe-child', '/_dev/chat-iframe-child', Record<never, never>, Record<never, never>>,
    '/_dev/chat-iframe-tools': RouteRecordInfo<'/_dev/chat-iframe-tools', '/_dev/chat-iframe-tools', Record<never, never>, Record<never, never>>,
    '/_dev/chat-mcp': RouteRecordInfo<'/_dev/chat-mcp', '/_dev/chat-mcp', Record<never, never>, Record<never, never>>,
    '/_dev/chat-subagent': RouteRecordInfo<'/_dev/chat-subagent', '/_dev/chat-subagent', Record<never, never>, Record<never, never>>,
    '/_dev/chat-vjsf': RouteRecordInfo<'/_dev/chat-vjsf', '/_dev/chat-vjsf', Record<never, never>, Record<never, never>>,
    '/_dev/summary': RouteRecordInfo<'/_dev/summary', '/_dev/summary', Record<never, never>, Record<never, never>>,
    '/[type]/[id]/chat': RouteRecordInfo<'/[type]/[id]/chat', '/:type/:id/chat', { type: ParamValue<true>, id: ParamValue<true> }, { type: ParamValue<false>, id: ParamValue<false> }>,
    '/[type]/[id]/settings': RouteRecordInfo<'/[type]/[id]/settings', '/:type/:id/settings', { type: ParamValue<true>, id: ParamValue<true> }, { type: ParamValue<false>, id: ParamValue<false> }>,
  }
}
