/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_dev/chat': RouteRecordInfo<
      '/_dev/chat',
      '/_dev/chat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_dev/chat-action': RouteRecordInfo<
      '/_dev/chat-action',
      '/_dev/chat-action',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_dev/chat-drawer': RouteRecordInfo<
      '/_dev/chat-drawer',
      '/_dev/chat-drawer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_dev/chat-iframe': RouteRecordInfo<
      '/_dev/chat-iframe',
      '/_dev/chat-iframe',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_dev/chat-iframe-2': RouteRecordInfo<
      '/_dev/chat-iframe-2',
      '/_dev/chat-iframe-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_dev/chat-iframe-child': RouteRecordInfo<
      '/_dev/chat-iframe-child',
      '/_dev/chat-iframe-child',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_dev/chat-iframe-tools': RouteRecordInfo<
      '/_dev/chat-iframe-tools',
      '/_dev/chat-iframe-tools',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_dev/chat-mcp': RouteRecordInfo<
      '/_dev/chat-mcp',
      '/_dev/chat-mcp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_dev/chat-menu': RouteRecordInfo<
      '/_dev/chat-menu',
      '/_dev/chat-menu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_dev/chat-subagent': RouteRecordInfo<
      '/_dev/chat-subagent',
      '/_dev/chat-subagent',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_dev/chat-vjsf': RouteRecordInfo<
      '/_dev/chat-vjsf',
      '/_dev/chat-vjsf',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_dev/summary': RouteRecordInfo<
      '/_dev/summary',
      '/_dev/summary',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[type]/[id]/chat': RouteRecordInfo<
      '/[type]/[id]/chat',
      '/:type/:id/chat',
      { type: ParamValue<true>, id: ParamValue<true> },
      { type: ParamValue<false>, id: ParamValue<false> },
      | never
    >,
    '/[type]/[id]/settings': RouteRecordInfo<
      '/[type]/[id]/settings',
      '/:type/:id/settings',
      { type: ParamValue<true>, id: ParamValue<true> },
      { type: ParamValue<false>, id: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/_dev/chat.vue': {
      routes:
        | '/_dev/chat'
      views:
        | never
    }
    'src/pages/_dev/chat-action.vue': {
      routes:
        | '/_dev/chat-action'
      views:
        | never
    }
    'src/pages/_dev/chat-drawer.vue': {
      routes:
        | '/_dev/chat-drawer'
      views:
        | never
    }
    'src/pages/_dev/chat-iframe.vue': {
      routes:
        | '/_dev/chat-iframe'
      views:
        | never
    }
    'src/pages/_dev/chat-iframe-2.vue': {
      routes:
        | '/_dev/chat-iframe-2'
      views:
        | never
    }
    'src/pages/_dev/chat-iframe-child.vue': {
      routes:
        | '/_dev/chat-iframe-child'
      views:
        | never
    }
    'src/pages/_dev/chat-iframe-tools.vue': {
      routes:
        | '/_dev/chat-iframe-tools'
      views:
        | never
    }
    'src/pages/_dev/chat-mcp.vue': {
      routes:
        | '/_dev/chat-mcp'
      views:
        | never
    }
    'src/pages/_dev/chat-menu.vue': {
      routes:
        | '/_dev/chat-menu'
      views:
        | never
    }
    'src/pages/_dev/chat-subagent.vue': {
      routes:
        | '/_dev/chat-subagent'
      views:
        | never
    }
    'src/pages/_dev/chat-vjsf.vue': {
      routes:
        | '/_dev/chat-vjsf'
      views:
        | never
    }
    'src/pages/_dev/summary.vue': {
      routes:
        | '/_dev/summary'
      views:
        | never
    }
    'src/pages/[type]/[id]/chat.vue': {
      routes:
        | '/[type]/[id]/chat'
      views:
        | never
    }
    'src/pages/[type]/[id]/settings.vue': {
      routes:
        | '/[type]/[id]/settings'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
