/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentChat: typeof import('./src/components/AgentChat.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VjsfPutReq: typeof import('./src/components/vjsf/vjsf-put-req.vue')['default']
    VjsfPutReqEn: typeof import('./src/components/vjsf/vjsf-put-req-en.vue')['default']
    VjsfPutReqFr: typeof import('./src/components/vjsf/vjsf-put-req-fr.vue')['default']
  }
}
