/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountSelector: typeof import('./src/components/AccountSelector.vue')['default']
    AgentChat: typeof import('./src/components/AgentChat.vue')['default']
    AgentChatDebugDialog: typeof import('./src/components/agent-chat/AgentChatDebugDialog.vue')['default']
    AgentChatHeader: typeof import('./src/components/agent-chat/AgentChatHeader.vue')['default']
    AgentChatInput: typeof import('./src/components/agent-chat/AgentChatInput.vue')['default']
    AgentChatMessages: typeof import('./src/components/agent-chat/AgentChatMessages.vue')['default']
    AutonomousAgentRunStatus: typeof import('./src/components/AutonomousAgentRunStatus.vue')['default']
    AutonomousAgentsSection: typeof import('./src/components/AutonomousAgentsSection.vue')['default']
    ConversationReview: typeof import('./src/components/ConversationReview.vue')['default']
    EvaluatorChat: typeof import('./src/components/EvaluatorChat.vue')['default']
    FormActions: typeof import('./src/components/FormActions.vue')['default']
    LiveToolsPanel: typeof import('./src/components/dev/LiveToolsPanel.vue')['default']
    MarkdownContent: typeof import('./src/components/agent-chat/MarkdownContent.vue')['default']
    ModerationSection: typeof import('./src/components/ModerationSection.vue')['default']
    MonitoringAccountHistogram: typeof import('./src/components/MonitoringAccountHistogram.vue')['default']
    MonitoringGlobalSection: typeof import('./src/components/MonitoringGlobalSection.vue')['default']
    MonitoringIndividualSection: typeof import('./src/components/MonitoringIndividualSection.vue')['default']
    MonitoringPlatformSection: typeof import('./src/components/MonitoringPlatformSection.vue')['default']
    MonitoringUserHistogram: typeof import('./src/components/MonitoringUserHistogram.vue')['default']
    OrgConfigSection: typeof import('./src/components/OrgConfigSection.vue')['default']
    QuotasTable: typeof import('./src/components/QuotasTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TraceComparePicker: typeof import('./src/components/TraceComparePicker.vue')['default']
    TraceConsentSheet: typeof import('./src/components/agent-chat/TraceConsentSheet.vue')['default']
    TraceReview: typeof import('./src/components/TraceReview.vue')['default']
    TracesSection: typeof import('./src/components/TracesSection.vue')['default']
    TraceView: typeof import('./src/components/agent-chat/TraceView.vue')['default']
    UsageCard: typeof import('./src/components/UsageCard.vue')['default']
    VjsfAutonomousAgentWriteReq: typeof import('./src/components/vjsf/vjsf-autonomous-agent-write-req.vue')['default']
    VjsfAutonomousAgentWriteReqEn: typeof import('./src/components/vjsf/vjsf-autonomous-agent-write-req-en.vue')['default']
    VjsfAutonomousAgentWriteReqFr: typeof import('./src/components/vjsf/vjsf-autonomous-agent-write-req-fr.vue')['default']
    VjsfOrgFormModels: typeof import('./src/components/vjsf/vjsf-org-form-models.vue')['default']
    VjsfOrgFormModelsEn: typeof import('./src/components/vjsf/vjsf-org-form-models-en.vue')['default']
    VjsfOrgFormModelsFr: typeof import('./src/components/vjsf/vjsf-org-form-models-fr.vue')['default']
    VjsfOrgFormModeration: typeof import('./src/components/vjsf/vjsf-org-form-moderation.vue')['default']
    VjsfOrgFormModerationEn: typeof import('./src/components/vjsf/vjsf-org-form-moderation-en.vue')['default']
    VjsfOrgFormModerationFr: typeof import('./src/components/vjsf/vjsf-org-form-moderation-fr.vue')['default']
    VjsfPutReq: typeof import('./src/components/vjsf/vjsf-put-req.vue')['default']
    VjsfPutReqEn: typeof import('./src/components/vjsf/vjsf-put-req-en.vue')['default']
    VjsfPutReqFr: typeof import('./src/components/vjsf/vjsf-put-req-fr.vue')['default']
    WorkflowDetail: typeof import('./src/components/dev/WorkflowDetail.vue')['default']
    WorkflowWizard: typeof import('./src/components/dev/WorkflowWizard.vue')['default']
  }
}
