/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentChat: typeof import('./src/components/AgentChat.vue')['default']
    AgentChatDebugDialog: typeof import('./src/components/agent-chat/AgentChatDebugDialog.vue')['default']
    AgentChatHeader: typeof import('./src/components/agent-chat/AgentChatHeader.vue')['default']
    AgentChatInput: typeof import('./src/components/agent-chat/AgentChatInput.vue')['default']
    AgentChatMessages: typeof import('./src/components/agent-chat/AgentChatMessages.vue')['default']
    MonitoringAccountHistogram: typeof import('./src/components/MonitoringAccountHistogram.vue')['default']
    MonitoringGlobalSection: typeof import('./src/components/MonitoringGlobalSection.vue')['default']
    MonitoringIndividualSection: typeof import('./src/components/MonitoringIndividualSection.vue')['default']
    MonitoringUserHistogram: typeof import('./src/components/MonitoringUserHistogram.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UsageCard: typeof import('./src/components/UsageCard.vue')['default']
    VjsfPutReq: typeof import('./src/components/vjsf/vjsf-put-req.vue')['default']
    VjsfPutReqEn: typeof import('./src/components/vjsf/vjsf-put-req-en.vue')['default']
    VjsfPutReqFr: typeof import('./src/components/vjsf/vjsf-put-req-fr.vue')['default']
  }
}
